config/routes.rb
Rails.application.routes.draw do
  root to: "about#index"

  resources "teams", only: %i[index show]
  resources "players", only: %i[index show]
  resources "games", only: %i[index show]
  resources "seasons", only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :home_team, :class_name => 'Team'
  belongs_to :visitor_team, :class_name => 'Team'

  validates :home_team_score, numericality: { only_integer: true}
  validates :visitor_team_score, numericality: { only_integer: true}
  validates :season, numericality: { only_integer: true}
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :seasons

  validates :first_name, :last_name, presence: true
  validates :weight, numericality: { only_integer: true}
  validates :height_feet, numericality: { only_integer: true}
  validates :height_inches, numericality: { only_integer: true}
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :player
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players

  has_many :home_teams, :class_name => 'Game', :foreign_key => ':home_team_id'
  has_many :visitor_teams, :class_name => 'Game', :foreign_key => ':visitor_team_id'

  validates :name, :city, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.includes(:team).order(:first_name)
  end

  def show
    @player = Player.includes(:team).find(params[:id])
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    @seasons = Season.all
  end

  def show
    @season = Season.find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/about/index.html.erb
<h2>About Us:</h2>
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <p>
        This NBA stats app contains player data from all players since the 1979
        season until the current season. (With the exception of player headshots,
        which are from the 2018 season. Sorry.) Click the links above to navigation
        to different stats pages on Players, Teams, Games and Player Season Averages.
      </p>
    </div>
    <div class="col-lg-6">
      <p>
        The data is pulled from two sources (which are luckily free. Thank you to
        the creators):
      </p>
      <ul>
        <li>NBA Stats API: <a href="https://www.balldontlie.io/#introduction">balldontlie.io</a></li>
        <li>NBA Player API: <a href="https://nba-players.herokuapp.com/">nba-players.herokuapp.com/</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<h2>Listed NBA Games</h2>

<% if @games.empty? %>
 <p>There are no available games. Call Adam Silver ASAP!</p>
<% else %>
  <ul>
    <% @games.each do |game| %>
      <li>
        <%= game.visitor_team_id %> @ <%= game.home_team_id %>
        Home Team Score: <%= game.home_team_score %>
        Visitor Team Score: <%= game.visitor_team_score %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "NBA Stats App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "NBA Stats App" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
      <div class="jumbotron text-center">
        <img src="https://pngimg.com/uploads/nba/nba_PNG14.png" alt="" width="75">
        <h1>
          Welcome to NBA's Unofficial Stats App
        </h1>
        <p>
          <%= link_to 'Home', root_path, :class => "btn btn-primary btn-sm" %>
          <%= link_to 'Teams', teams_path, :class => "btn btn-primary btn-sm" %>
          <%= link_to 'Players', players_path, :class => "btn btn-primary btn-sm" %>
          <%= link_to 'Seasons', seasons_path, :class => "btn btn-primary btn-sm" %>
          <%= link_to 'Games', games_path, :class => "btn btn-primary btn-sm" %>
        </p>
      </div>
      </header>
      <%= yield %>
      <footer>
        Copywrong NBA 2020
      </footer>
    </div>
  </body>
</html>

app/views/players/index.html.erb
<h2>All <%= @players.count %> NBA Players</h2>

<% if @players.empty? %>
 <p>There are no players in the league. Call Adam Silver ASAP!</p>
<% else %>
  <ul>
    <% @players.each do |player| %>
      <li>
        <%= link_to "#{player.first_name} #{player.last_name}", player %> of the
        <%= link_to "#{player.team.city} #{player.team.name}", player.team %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/players/show.html.erb
<h2><%= @player.first_name %> <%= @player.last_name %> (<%= link_to @player.team.abbreviation, @player.team %>)</h2>

<div class="container">
  <div class="row">
    <img src="<%= @player.photo %>" alt="No photo available"/>
    <ul>
      <li>Team: <%= link_to "#{@player.team.city} #{@player.team.name}", @player.team %> </li>
      <li>Position: <%= @player.position %></li>
      <li>Height: <%= @player.height_feet %>'<%= @player.height_inches %>"</li>
      <li>Weight: <%= @player.weight %> lbs</li>
      <li>Favourite Dragonball Character: <%= @player.fav_db_character %></li>
    </ul>
  </div>

</div>

app/views/seasons/index.html.erb
<h2>NBA <%= @seasons.first.season %>-<%= @seasons.first.season + 1 %> Season Stats</h2>

<% if @seasons.empty? %>
 <p>There are no recorded seasons found. Call Adam Silver ASAP! Or Dr. Strange?</p>
<% else %>
  <ul>
    <% @seasons.each do |season| %>
      <li>
        <%= link_to "#{season.season} Stats", season %> for <%= link_to "#{season.player.first_name} #{season.player.last_name}", season.player %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/seasons/show.html.erb
<h2>
  <%= @season.season %>-<%= @season.season + 1 %> Season Averages for
  <%= @season.player.first_name %> <%= @season.player.last_name %>
  (<%= link_to @season.player.team.abbreviation, @season.player.team %>)
</h2>

<img src="<%= @season.player.photo %>" alt="Photo not available">
<ul>
  <li>Games Played: <%= @season.games_played %></li>
  <li>Minutes: <%= @season.min %></li>
  <li>Points: <%= @season.pts %></li>
  <li>Assists: <%= @season.ast %></li>
  <li>Steals: <%= @season.stl %></li>
  <li>Blocks: <%= @season.blk %></li>
  <li>Field Goals Made: <%= @season.fgm %></li>
  <li>Field Goals Attempted: <%= @season.fga %></li>
  <li>Field Goals %: <%= @season.fg_pct %></li>
  <li>3-points Made: <%= @season.fg3m %></li>
  <li>3-points Attempted: <%= @season.fg3a %></li>
  <li>3-points %: <%= @season.fg3_pct %></li>
  <li>Free Throws Made: <%= @season.ftm %></li>
  <li>Free Throws Attempted: <%= @season.fta %></li>
  <li>Free Throws %: <%= @season.ft_pct %></li>
  <li>Offensive Rebounds: <%= @season.oreb %></li>
  <li>Defensive Rebounds: <%= @season.dreb %></li>
  <li>Overall Rebounds: <%= @season.reb %></li>
  <li>Turnovers: <%= @season.turnover %></li>
  <li>Personal Fouls: <%= @season.pf %></li>
</ul>